### ISSUE TITLE
想問一下當初是在哪個作業系統執行？

### ISSUE THREAD

**Issue by SonodaKazuto** [wasabi-neko/nvmain-gen5-HW#1]
如題，想問一下當初是在哪個作業系統執行的，因為我也嘗試在 macOS 上用 docker 來做，配置也都一樣，可是 gem5 都不能 build 成功，雖然我不是很確定跟平台有沒有關，但是還是想問一下，謝謝。

**Comment by wasabi-neko** [comment]
我當時是在 Ubuntu 20.04.4 LTS 上執行的，不過 gem5 的 build 發生在 docker 內部所以應該跟主機平台沒有關西，大概八

**Comment by SonodaKazuto** [comment]
恩恩應該是吧，我後來調記憶體就成功了，現在是遇到其他問題，謝謝
