### ISSUE TITLE
gem5+NVmain build up

### ISSUE THREAD

**Issue by claire8967** [wasabi-neko/nvmain-gen5-HW#3]
不好意思,
我在 build gem5 + NVmain 環境時一直沒有成功,
想問下能不能跟您拿一下 build 的教學 ?

**Comment by wasabi-neko** [comment]
抱歉，當時的簡報我目前找不太到了，如果以後有找到我再補上去。
不過 build 方式了話 README 中的討論筆記裡面有提到，在 gen5 目錄下執行｀scons EXTRAS=../NVmain build/X86/gem5.opt｀ 便可。

**Comment by claire8967** [comment]
好的，非常謝謝你的回覆
